# Generated by Django 4.1.13 on 2025-04-26 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('shift', models.CharField(choices=[('morning', 'Sáng (7h-12h)'), ('afternoon', 'Chiều (12h-17h)'), ('evening', 'Tối (17h-22h)'), ('full_day', 'Cả ngày (7h-22h)')], max_length=20)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ngày làm việc')),
                ('schedule_status', models.BooleanField(default=True, verbose_name='Trạng thái lịch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staff'),
        ),
    ]
