# Generated by Django 4.1.13 on 2025-04-26 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_parkingrecord_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá tiếp theo (/30 phút)'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='first_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá đầu tiên (1h)'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên loại xe'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='overnight_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá qua đêm'),
        ),
    ]
