# Generated by Django 3.2.25 on 2025-05-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
