# Generated by Django 3.2.25 on 2025-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
